spring.datasource.url=jdbc:postgresql://localhost:5433/dropzone
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

stripe.api.key=sk_test_51ThwQEL6lMOPDss4454NfNz5B86iL4uLWVd75P7rYtaeXX84vsD80ZSzS8615XU9IP4CAiuHyOvxpBjvl4oH0x7100fJuZmaKv
stripe.webhook.secret=whsec_e52e749d449947050d6228db6cde8cd6e234cbc0a07cb59432235e6432305618

server.port=8081
